import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/component/common/header";
import Footer from "@/app/component/common/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
